### PR TITLE
feat: Add Frontier Wallet support

### PR DESCRIPTION
**Pull request by akash-frontier**
Official Website:
https://www.frontier.xyz/

Chrome Extension Url:
https://chrome.google.com/webstore/detail/frontier-wallet/kppfdiipphfccemcignhifpjkapfbihd

### CODE REVIEW

**Comment by raop155** [comment]
Hey @akash-frontier can check/review #53 too?
Is the same but for Kucoin Wallet :) and some refactor in the codebase,

**Comment by akash-frontier** [comment]
Hi @raop155 PR looks good, will follow the same once & update here once it gets merged.

**Comment by M-Picco** [comment]
@akash-frontier I've tried checking out the branch and running it locally, but I got the following error when running it:

```
ERROR in src/contexts/InjectiveWalletContext.tsx:45:20
TS2339: Property 'Frontier' does not exist on type 'typeof Wallet'.
    43 |   },
    44 |   {
  > 45 |     wallet: Wallet.Frontier,
       |                    ^^^^^^^^
    46 |     name: "Frontier Wallet",
    47 |     isInstalled: typeof (window as any).frontier.cosmos !== "undefined",
    48 |     icon: FrontierIcon,
```

Are the injective package versions the ones they should be?

**Comment by raop155** [comment]
@M-Picco as we are reviewing evm `wallet aggregator` integration, prob is not needed this?

**Comment by M-Picco** [comment]
> @M-Picco as we are reviewing evm `wallet aggregator` integration, prob is not needed this?

@raop155 Partially.

The changes in PR #61 should detect Frontier for EVM chains (I've already added the icon as well). 

However, there's nothing yet for Injective; but we'll get there when I open the PR for that chain. There's the version issues I commented above that have to be sorted out though.

**Pull request closed without merging**
